pod:
  annotations: {}
  envFrom: {}
  labels: {}
  replicas: 1
  templateArgs:
    # Gives very high priority to kube-vip
    priorityClassName: system-cluster-critical
    hostNetwork: true
    # By default, forces Kube-vip to run on control plane nodes 
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
    # Even if a node specifically requests not to run Pods, kube-vip will run anyway
    tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists

service:
  annotations: {}
  clusterIP: ""
  labels: {}
  loadBalancerIP: "" 
  type: ClusterIP