apiVersion: v2
name: nfs
version: 3.0.0
description: NFS server for providing network storage to a cluster
type: application
home: https://github.com/constellation-net/charts
maintainers:
  - name: Jack Gledhill
    email: me@jackgledhill.com
    url: https://jacksoftware.co.uk
dependencies:
  - name: common
    version: 3.0.0
    repository: https://charts.starsystem.dev