common:
  namespace: nfs

pods:
  affinity: {}
  annotations: {}
  dnsPolicy: ""
  hostNetwork: false
  labels: {}
  priorityClassName: ""
  replicas: 1
  tolerations: []

rbac:
  create: true
  serviceAccountName: '{{ include "common.name" . }}'
  subjects: []

nfs:
  provisioner: nfs.starsystem.dev
  volume:
    name: nfs # Name of the PersistentVolume that will be claimed by the NFS server
    storageClassName: local # Name of the storage class that the PVC will use
    capacity: 100Gi