apiVersion: v2
name: common
version: 1.0.2
description: Library Helm Chart for Constellation's Helm Repository
type: library
home: https://github.com/constellation-net/charts
maintainers:
  - name: Jack Gledhill
    email: me@jackgledhill.com
    url: https://jacksoftware.co.uk