common:
  namespace: default

pods:
  affinity: {}
  annotations: {}
  dnsPolicy: ""
  hostNetwork: false
  labels: {}
  priorityClassName: ""
  replicas: 1
  tolerations: []

rbac:
  create: false
  serviceAccountName: '{{ include "common.name" . }}'
  subjects: []