{{ include "common.Service" (list . "wireguard.Service") }}

{{- define "wireguard.Service" -}}
spec:
  ports:
    - name: wireguard
      port: 51820
      targetPort: 51820
      protocol: UDP
    - name: dashboard
      port: 8888
      targetPort: 8888
      protocol: TCP
{{- end -}}