apiVersion: v2
name: mc-router
version: 1.0.2
description: Reverse Proxy for Constellation's Minecraft servers, using K8s service-discovery
type: application
home: https://github.com/constellation-net/charts
maintainers:
  - name: Jack Gledhill
    email: me@jackgledhill.com
    url: https://jacksoftware.co.uk
dependencies:
  - name: common
    version: 2.0.2
    repository: https://charts.starsystem.dev