{{ include "common.Deployment" (list . "ddns.Deployment") }}

{{- define "ddns.Deployment" -}}
spec:
  template:
    spec:
      containers:
        - name: ddns
          image: timothyjmiller/cloudflare-ddns:latest
          env:
            - name: CONFIG_PATH
              value: /etc/ddns/
          resources:
            requests:
              cpu: 100m
              memory: 50M
          volumeMounts:
            # Mounts the volume that has the config file
            - name: config
              mountPath: /etc/ddns
              readOnly: true
{{- end -}}