# Modified version of: https://raw.githubusercontent.com/kube-vip/kube-vip-cloud-provider/main/manifest/kube-vip-cloud-controller.yaml
{{ include "common.rbac.ClusterRole" (list . "kubeVipLb.ClusterRole") }}
---
{{ include "common.rbac.ClusterRoleBinding" . }}
---
{{ include "common.rbac.ServiceAccount" . }}

{{- define "kubeVipLb.ClusterRole" -}}
rules:
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - "leases"
    verbs:
      - "get"
      - "create"
      - "update"
      - "list"
      - "put"
      - 
  - apiGroups:
      - ""
    resources:
      - "configmaps"
      - "endpoints"
      - "events"
      - "services/status"
      - "leases"
    verbs:
      - "*"

  - apiGroups:
      - ""
    resources:
      - "nodes"
      - "services"
    verbs:
      - "list"
      - "get"
      - "watch"
      - "update"
{{- end -}}