{{- define "common.SelfAntiAffinity" -}}
# Prevents multiple replicas on the same node
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            {{ include "common.PodLabels" . | nindent 12 }}
        topologyKey: kubernetes.io/hostname
{{- end -}}