{{- define "common._daemonset" -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
{{ with .Values.pod.annotations }}
  annotations:
    {{ toYaml . | nindent 2 }}
{{ end }}
spec:
  selector:
    matchLabels:
      {{ include "common.PodLabels" . | nindent 8 }}
  template:
    metadata:
      labels:
        {{ include "common.PodLabels" . | nindent 8 }}
    spec:
    {{ with .Values.pod.templateArgs }}
      {{ toYaml . | nindent 6 }}
    {{ end }}
      hostname: {{ .Release.Name }}
      terminationGracePeriodSeconds: 30
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
      serviceAccountName: {{ tpl (.Values.pod.serviceAccount | default .Release.Name) . }}
{{- end -}}

{{- define "common.DaemonSet" -}}
{{ include "common.util.merge" (append . "common._daemonset") }}
{{- end -}}