{{- define "common.deploymentoverrides" -}}
kind: Deployment
spec:
  replicas: {{ .Values.pod.replicas | default 1 }}
{{- end -}}

{{- define "common.deployment" -}}
{{ include "common.DaemonSet" (list . "common.deploymentoverrides") }}
{{- end -}}

{{- define "common.Deployment" -}}
{{ include "common.util.merge" (append . "common.deployment") }}
{{- end -}}