{{- define "common._base.clusterrole" -}}
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
        name: {{ tpl .Values.metaName }}
    roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: {{ tpl .Values.metaName }}
    subjects:
        - kind: ServiceAccount
          name: {{ tpl .Values.metaName }}
          namespace: {{ .Values.namespace }}
{{- end -}}

{{- define "common.resource.clusterrole" -}}
    {{- include "common.helper.merge" (append . "common._base.clusterrole") -}}
{{- end -}}