{{- define "common._clusterrole" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{- include "common.variables.name" . -}}
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
{{- end -}}

{{- define "common.ClusterRole" -}}
{{- include "common.util.merge" (append . "common._clusterrole") -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{- include "common.variables.name" . -}}
subjects:
  - kind: ServiceAccount
    name: {{- include "common.variables.name" . -}}
    namespace: {{ tpl .Values.namespace . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{- include "common.variables.name" . -}}
{{- end -}}