{{- define "common.Labels" -}}
app: {{ .Chart.Name }}
release: {{ .Release.Name }}
{{- end -}}

{{- define "common.PodLabels" -}}
{{ include "common.Labels" . }}
{{ with .Values.pod.labels }}
{{ toYaml . }}
{{ end }}
{{- end -}}

{{- define "common.EnvFrom" -}}
{{ with .Values.pod.envFrom }}
envFrom:
  {{ toYaml . | nindent 2 }}
{{ end }}
{{- end -}}