{{- define "common._daemonset" -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{- include "common.variables.name" . -}}
  namespace: {{ tpl .Values.namespace . }}
spec:
  selector:
    matchLabels:
      {{- include "common.variables.labels" . | nindent 6 -}}
  template:
    metadata:
      labels:
        {{- include "common.variables.labels" . | nindent 8 -}}
    {{- include "common.partials.PriorityClass" . | nindent 4 -}}
    {{- include "common.partials.ServiceAccount" . | nindent 4 -}}
    hostname: {{- include "common.variables.name" . -}}
    restartPolicy: Always
{{- end -}}

{{- define "common.DaemonSet" -}}
{{- include "common.util.merge" (append . "common._daemonset") -}}
{{- end -}}