{{- define "common._deployment" -}}
apiVersion: v1
kind: Deployment
metadata:
  name: {{ include "common.variables.name" . }}
  namespace: {{ tpl .Values.namespace . }}
spec:
  selector:
    matchLabels:
      {{ include "common.variables.labels" . | nindent 6 }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        {{ include "common.variables.labels" . | nindent 8 }}
    spec:
      restartPolicy: Always
      hostname: {{ include "common.variables.name" . }}
      {{ include "common.partials.affinity" . | nindent 6 }}
      {{- include "common.partials.ServiceAccount" . -}}
      {{- include "common.partials.PriorityClass" . -}}
{{- end -}}

{{- define "common.Deployment" -}}
{{- include "common.util.merge" (append . "common._deployment") -}}
{{- end -}}