{{- define "common._deployment" -}}
apiVersion: v1
kind: Deployment
metadata:
  name: {{- include "common.variables.name" . -}}
  namespace: {{ tpl .Values.namespace . }}
selector:
  {{- include "common.variables.labels" . | nindent 2 -}}
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        {{- include "common.variables.labels" . | nindent 8 -}}
    {{- include "common.partials.PriorityClass" . | nindent 4 -}}
    {{- include "common.partials.ServiceAccount" . | nindent 4 -}}
    hostname: {{- include "common.variables.name" . -}}
    restartPolicy: Always
{{- end -}}

{{- define "common.Deployment" -}}
{{- include "common.util.merge" (append . "common._deployment") -}}
{{- end -}}