{{- define "common._base.ingress" -}}
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
        name: {{ tpl .Values.metaName }}
        namespace: {{ .Values.namespace }}
{{- end -}}

{{- define "common.resource.ingress" -}}
    {{- include "common.helper.merge" (append . "common._base.ingress") -}}
{{- end -}}