{{- define "common._base.priorityclass" -}}
    apiVersion: scheduling.k8s.io/v1
    kind: PriorityClass
    metadata:
        name: {{ tpl .Values.metaName }}
{{- end -}}

{{- define "common.resource.priorityclass" -}}
    {{- include "common.helper.merge" (append . "common._base.priorityclass") -}}
{{- end -}}