{{- define "common._base.secret" -}}
    apiVersion: v1
    kind: Secret
    metadata:
        name: {{ tpl .Values.metaName }}
    type: Opaque
    data: {}
    stringData: ""
{{- end -}}

{{- define "common.resource.secret" -}}
    {{- include "common.helper.merge" (append . "common._base.secret") -}}
{{- end -}}