{{- define "common._base.service" -}}
    apiVersion: v1
    kind: Service
    metadata:
        name: {{ tpl .Values.metaName }}
        namespace: {{ .Values.namespace }}
    spec:
        selector:
            app: {{ tpl .Values.selectorLabel }}
{{- end -}}

{{- define "common.resource.service" -}}
    {{- include "common.helper.merge" (append . "common._base.service") -}}
{{- end -}}