{{- define "common._base.serviceaccount" -}}
    apiVersion: v1
    kind: ServiceAccount
    metadata:
        name: {{ tpl .Values.metaName }}
        namespace: {{ .Values.namespace }}
{{- end -}}

{{- define "common.resource.serviceaccount" -}}
    {{- include "common.helper.merge" (append . "common._base.serviceaccount") -}}
{{- end -}}