{{- define "common._service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{- include "common.variables.name" -}}
  namespace: {{ tpl .Values.namespace }}
type: ClusterIP
spec:
  selector:
    {{- include "common.variables.labels" -}}
{{- end -}}

{{- define "common.Service" -}}
{{- include "common.util.merge" (append . "common._service") -}}
{{- end -}}