{{- define "common._serviceaccount" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "common.variables.name" . }}
  namespace: {{ tpl .Values.namespace . }}
{{- end -}}

{{- define "common.ServiceAccount" -}}
{{- include "common.util.merge" (append . "common._serviceaccount") -}}
{{- end -}}