{{- define "common._service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.variables.name" . }}
  namespace: {{ tpl .Values.namespace . }}
spec:
  type: ClusterIP
  selector:
    {{ include "common.variables.labels" . | nindent 4 }}
{{- end -}}

{{- define "common.Service" -}}
{{- include "common.util.merge" (append . "common._service") -}}
{{- end -}}