{{- define "pathProvisioner.helperPod" -}}
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-helper
  namespace: {{ .Release.Namespace }}
spec:
  priorityClassName: system-node-critical
  tolerations:
    - key: node.kubernetes.io/disk-pressure
      operator: Exists
      effect: NoSchedule
  containers:
    - name: helper
      image: rancher/mirrored-library-busybox:1.36.1
{{- end -}}