pod:
  annotations: {}
  labels: {}
  replicas: 1
  serviceAccount: default
  templateArgs:
    volumes:
      - name: config
        configMap:
          name: prometheus-config

service:
  annotations: {}
  clusterIP: ""
  labels: {}
  loadBalancerIP: "" 
  type: ClusterIP

pvc:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""