{{ include "common.pods.Deployment" (list . "wireguard.Deployment") }}

{{- define "wireguard.Deployment" -}}
spec:
  template:
    spec:
      containers:
        name: wireguard
          image: ghcr.io/wg-easy/wg-easy:latest
          ports:
            - name: wireguard
              containerPort: 51820
            - name: ui
              containerPort: 51821
          securityContext:
            capabilities:
              add:
                - SYS_MODULE
                - NET_ADMIN
          env:
            - name: LANG
              value: en
            - name: WG_PERSISTENT_KEEPALIVE
              value: 25
            - name: WG_MTU
              value: 1500
            - name: WG_PORT
              value: 51820
            - name: UI_TRAFFIC_STATS
              value: true
            - name: UI_CHART_TYPE
              value: 1
            - name: WG_HOST
              value: {{ tpl .Values.wireguard.publicAddress }}
            - name: WG_DEFAULT_ADDRESS
              value: {{ tpl .Values.wireguard.defaultAddress }}
            - name: WG_ALLOWED_IPS
              value: {{ tpl .Values.wireguard.allowedIps }}
            - name: WG_DEFAULT_DNS
              value: {{ tpl .Values.wireguard.defaultDns }}
            - name: PASSWORD_HASH
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.wireguard.passwordSecret.name }}
                  key: {{ .Values.wireguard.passwordSecret.key }}
                  optional: true
          volumeMounts:
            - name: peers
              mountPath: /etc/wireguard
              readOnly: true
      
      volumes:
        - name: peers
          persistentVolumeClaim:
            claimName: {{ tpl .Values.wireguard.pvcName }}
            readOnly: false
{{- end -}}