{{ include "common.net.Service" (list . "wireguard.Service") }}

{{- define "wireguard.Service" -}}
spec:
  ports:
    - name: wireguard
      port: 51820
      targetPort: 51820
      protocol: UDP
    - name: ui
      port: 51821
      targetPort: 51821
      protocol: TCP
{{- end -}}