pod:
  annotations: {}
  args: []
  envFrom: {}
  labels: {}
  replicas: 1
  serviceAccount: default
  templateArgs: {}

service:
  annotations: {}
  clusterIP: ""
  labels: {}
  loadBalancerIP: "" 
  type: ClusterIP

pvc:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""

# Ports that traffic will listen to and provide proxying for
entrypoints:
  - name: web # Name of the entrypoint
    port: 80
    protocol: TCP
  - name: websecure
    port: 443
    protocol: TCP

corsMiddleware:
  allowedMethods:
    - GET
    - PUT
    - POST
    - HEAD
    - OPTIONS
  allowedOrigins:
    - https://example.com
  allowCreds: true
  allowedHeaders:
    - "*"
  maxAge: 100