# This is the star of the show. This manifest deploys a Traefik container with a volume mount to the ConfigMap that contains Traefik's static configuration
{{ include "common.pods.Deployment" (list . "traefik.Deployment") }}

{{- define "traefik.Deployment" -}}
spec:
  template:
    spec:
      # Every time the Pod starts, this container runs to update the file permissions in the temporary volume
      # Credit to the folks here for documenting their solutions: https://github.com/traefik/traefik-helm-chart/issues/164
      initContainers:
        - name: acme-file-perms
          image: busybox:1.31.1
          command: ["sh", "-c", "touch /data/acme.json && chown 65532:65532 /data/acme.json && chmod -Rv 600 /data/acme.json"]
          volumeMounts:
            - name: certs
              mountPath: /data
      # Creates a single Traefik container with a ConfigMap mounted to provide the static configuration
      containers:
        - name: traefik
          image: traefik:v3.1
          args:
          {{ range $arg := .Values.traefik.cliArgs }}
            - {{ $arg }}
          {{ end }}
          ports:
          {{ range $entrypoint := .Values.traefik.entrypoints }}
            - name: {{ $entrypoint.name }}
              containerPort: {{ $entrypoint.port }}
              protocol: {{ $entrypoint.protocol }}
          {{ end }}
          envFrom:
            - secretRef:
                name: {{ tpl .Values.traefik.acmeSecret . }}
          volumeMounts:
            - name: certs
              mountPath: /data
      
      volumes:
        - name: certs
          emptyDir:
            sizeLimit: 50Mi
            medium: Memory
{{- end -}}