# This is the star of the show. This manifest deploys a Traefik container with a volume mount to the ConfigMap that contains Traefik's static configuration
{{ include "common.pods.Deployment" (list . "traefik.Deployment") }}

{{- define "traefik.Deployment" -}}
spec:
  template:
    spec:
      # Creates a single Traefik container with a ConfigMap mounted to provide the static configuration
      containers:
        - name: traefik
          image: traefik:v3.1
          args:
          {{ range $arg := .Values.traefik.cliArgs }}
            - {{ $arg }}
          {{ end }}
          ports:
          {{ range $entrypoint := .Values.traefik.entrypoints }}
            - name: {{ $entrypoint.name }}
              containerPort: {{ $entrypoint.port }}
              protocol: {{ $entrypoint.protocol }}
          {{ end }}
          envFrom:
            - secretRef:
                name: {{ tpl .Values.traefik.acmeCerts.secretName . }}
          volumeMounts:
            - name: certs
              mountPath: /data/acme.json
              readOnly: true
      
      volumes:
        - name: certs
          persistentVolumeClaim:
            claimName: {{ tpl .Values.traefik.acmeCerts.pvcName . }}
            readOnly: false
{{- end -}}