apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-cors
  namespace: {{ .Release.Namespace }}
spec:
  headers:
    accessControlAllowMethods: {{ toYaml .Values.corsMiddleware.allowedMethods | nindent 6 }}
    accessControlAllowHeaders: {{ toYaml .Values.corsMiddleware.allowedHeaders | nindent 6 }}
    accessControlAllowOriginList: {{ toYaml .Values.corsMiddleware.allowedOrigins | nindent 6 }}
    accessControlMaxAge: {{ .Values.corsMiddleware.maxAge }}
    accessControlAllowCredentials: {{ .Values.corsMiddleware.allowCreds }}