apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cors
  namespace: {{ include "common.namespace" . }}
spec:
  headers:
    accessControlAllowMethods: {{ toYaml .Values.traefik.cors.allowedMethods | nindent 6 }}
    accessControlAllowHeaders: {{ toYaml .Values.traefik.cors.allowedHeaders | nindent 6 }}
    accessControlAllowOriginList: {{ toYaml .Values.traefik.cors.allowedOrigins | nindent 6 }}
    accessControlMaxAge: {{ .Values.traefik.cors.maxAge }}
    accessControlAllowCredentials: {{ .Values.traefik.cors.allowCreds }}