# Primary proxy service, allows incoming HTTP connections to Traefik, which can then be proxied through to the rest of the cluster
{{ include "common.net.Service" (list . "traefik.Service") }}

{{- define "traefik.Service" -}}
{{ with .Values.traefik.service.annotations }}
metadata:
  annotations:
    {{ toYaml . | nindent 4 }}
{{ end }}
spec:
  type: {{ .Values.traefik.service.type }}
  {{ with .Values.traefik.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{ end }}
  ports:
  {{ range $entrypoint := .Values.traefik.entrypoints }}
    - name: {{ $entrypoint.name }}
      port: {{ $entrypoint.port }} # Incoming port
      targetPort: {{ $entrypoint.port }} # Container port to proxy to 
      protocol: {{ $entrypoint.protocol }}
  {{ end }}
{{- end -}}