{{ include "common.HeadlessService" (list . "postgresql.Service") }}
---
{{ include "common.Service" (list . "postgresql.Service") }}

{{- define "postgresql.Service" -}}
spec:
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
      protocol: TCP
    - name: prometheus
      port: 9187
      targetPort: 9187
      protocol: TCP
{{- end -}}