{{- define "common.clusterrole" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
{{- end -}}

{{- define "common.ClusterRole" -}}
{{ include "common.util.merge" (append . "common.clusterrole") }}
{{- end -}}