{{- define "common.role" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
{{- end -}}

{{- define "common.Role" -}}
{{ include "common.util.merge" (append . "common.role") }}
{{- end -}}