{{ include "common.PVC" . }}
---
{{ include "common.Deployment" (list . "minio.Deployment") }}

{{- define "minio.Deployment" -}}
spec:
  template:
    spec:
      containers:
        - name: minio
          image: quay.io/minio/minio
          args:
            - server
            - /data
            - --console-address
            - ":80"
          ports:
            - name: web
              port: 80
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
{{- end -}}