{{ include "common.PVC" . }}
---
{{ include "common.Deployment" (list . "minecraft.Deployment") }}

{{- define "minecraft.Deployment" -}}
spec:
  template:
    spec:
      containers:
        - name: minecraft
          image: itzg/minecraft-server
          ports:รฅรง
            - name: minecraft
              containerPort: 25565
          env:
            - name: EULA
              value: "true"
            - name: STOP_SERVER_ANNOUNCE_DELAY
              value: "30"
            - name: STOP_DURATION
              value: "30"
            - name: TZ
              value: Europe/London
            - name: SNOOPER_ENABLED
              value: "false"
            - name: ONLINE_MODE
              value: "true"
          {{ include "common.EnvFrom" . | nindent 10 }}
          resources:
            requests:
              cpu: 2
              memory: 2G 
          volumeMounts:
            - name: data
              mountPath: /data
              readOnly: false
              subPath: {{ .Release.Name }}
      
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}
            readOnly: false
{{- end -}}