{{ include "common.net.Service" (list . "minecraft.Service") }}

{{- define "minecraft.Service" -}}
{{ with .Values.minecraft.service.annotations }}
metadata:
  annotations:
    {{ toYaml . | nindent 4 }}
{{ end }}
spec:
  ports:
    # Minecraft server
    - port: 25565
      targetPort: 25565
{{- end -}}