{{ include "common.Deployment" (list . "mcrouter.Deployment") }}

{{- define "mcrouter.Deployment" -}}
spec:
  template:
    spec:
      containers:
        - name: router
          image: itzg/mc-router:latest
          args:
            - --in-kube-cluster # Enables kubernetes service discovery
          {{ with .Values.pod.args }}
            {{ toYaml . | nindent 12 }}
          {{ end }}
          ports:
            - name: minecraft
              containerPort: 25565
          resources:
            requests:
              cpu: 100m
              memory: 50M 
{{- end -}}