# Modified version of: https://github.com/itzg/mc-router/tree/master
{{ include "common.ClusterRole" (list . "mcrouter.ClusterRole") }}
---
{{ include "common.ClusterRoleBinding" . }}
---
{{ include "common.ServiceAccount" . }}

{{- define "mcrouter.ClusterRole" -}}
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - watch
      - list
{{- end -}}