{{ include "common.DaemonSet" (list . "kubevip.DaemonSet") }}

{{- define "kubevip.DaemonSet" -}}
spec:
  template:
    spec:
      containers:
        - name: kubevip
          image: ghcr.io/kube-vip/kube-vip:v0.4.0
          # Needs a bunch of permissions re networking
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - SYS_TIME
          args:
            - manager
          env:
            - name: cp_enable
              value: "true"
          {{ include "common.EnvFrom" . | nindent 10 }}
          resources:
            requests:
              cpu: 250m
              memory: 100M 
{{- end -}}