# Modified version of: https://kube-vip.io/manifests/rbac.yaml
{{ include "common.ClusterRole" (list . "kubevip.ClusterRole") }}
---
{{ include "common.ClusterRoleBinding" . }}
---
{{ include "common.ServiceAccount" . }}

{{- define "kubevip.ClusterRole" -}}
rules:
  # Read & modify Services and Endpoints
  - apiGroups:
      - ""
    resources:
      - "services"
      - "endpoints"
    verbs:
      - "list"
      - "get"
      - "watch"
      - "update"

  # Update service status
  - apiGroups:
      - ""
    resources:
      - "services/status"
    verbs:
      - "update"
  
  # Get and update Nodes
  - apiGroups:
      - ""
    resources:
      - "nodes"
    verbs:
      - "list"
      - "get"
      - "watch"
      - "update"
      - "patch"
  
  # Used for leader election
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - "leases"
    verbs:
      - "list"
      - "get"
      - "watch"
      - "update"
      - "create"
  
  # Read and modify EndpointSlices
  - apiGroups:
      - "discovery.k8s.io"
    resources:
      - "endpointslices"
    verbs:
      - "list"
      - "get"
      - "watch"
      - "update"
{{- end -}}