# Modified version of: https://kube-vip.io/manifests/rbac.yaml
{{ include "common.rbac.ClusterRole" (list . "kubeVip.ClusterRole") }}
---
{{ include "common.rbac.ClusterRoleBinding" . }}
---
{{ include "common.rbac.ServiceAccount" . }}

{{- define "kubeVip.ClusterRole" -}}
rules:
  # Read & modify Services and Endpoints
  - apiGroups:
      - ""
    resources:
      - "services"
    verbs:
      - "list"
      - "get"
      - "watch"
      - "update"
  
  # Get and update Nodes
  - apiGroups:
      - ""
    resources:
      - "nodes"
    verbs:
      - "list"
      - "get"
      - "watch"
      - "update"
      - "patch"
  
  # Used for leader election
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - "leases"
    verbs:
      - "list"
      - "get"
      - "watch"
      - "update"
      - "create"
      - "put"
  
  # Read and modify EndpointSlices
  - apiGroups:
      - "discovery.k8s.io"
    resources:
      - "endpointslices"
    verbs:
      - "list"
      - "get"
      - "watch"
      - "update"

  - apiGroups:
      - ""
    resources:
      - "configmaps"
      - "endpoints"
      - "events"
      - "services/status"
      - "leases"
    verbs:
      - "*"
{{- end -}}