{{ include "common.PVC" . }}
---
{{ include "common.Deployment" (list . "nfs.Deployment") }}

{{- define "nfs.Deployment" -}}
spec:
  template:
    spec:
      containers:
        - name: nfs-server
          image: itsthenetwork/nfs-server-alpine:latest-arm
          # Unfortunately this is required for just about every NFS server in existence
          # As the NFS server is internal, the attack vector is hopefully quite small
          securityContext:
            privileged: true
          # Image supports other versions of NFS, but forcing the latest stable version is a good idea
          ports:
            - name: nfsv4
              containerPort: 2049
          env:
            # Waits for changes to be commited before replying to requests
            # Not as fast as async mode, but avoids data corruption due to a sudden crash
            - name: SYNC
              value: "true"
            - name: SHARED_DIRECTORY
              value: /export
          resources:
            requests:
              cpu: 100m
              memory: 100M 
          volumeMounts:
            # Bind mount to a local directory where files will be stored on disk
            - name: local
              mountPath: /export
              readOnly: false

      volumes:
        # PersistentVolume mapping a local directory from one node to the NFS server
        - name: local
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}
            readOnly: false
{{- end -}}