{{ include "common.volumes.PersistentVolumeClaim" (list . "nfs.PersistentVolumeClaim") }}

{{- define "nfs.PersistentVolumeClaim" -}}
spec:
  storageClassName: {{ tpl .Values.nfs.volume.storageClassName . }}
  volumeName: {{ tpl .Values.nfs.volume.name . }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.nfs.volume.capacity }}
{{- end -}}