{{ include "common.rbac.ClusterRole" (list . "nfs.ClusterRole") }}
---
{{ include "common.rbac.ClusterRoleBinding" . }}
---
{{ include "common.rbac.Role" (list . "nfs.Role") }}
---
{{ include "common.rbac.RoleBinding" . }}
---
{{ include "common.rbac.ServiceAccount" . }}

{{- define "nfs.ClusterRole" -}}
rules:
  # Allows fetching node data
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  # Creates PersistentVolumes for each PVC using the StorageClass
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
    verbs:
      - get
      - list
      - watch
      - create
      - delete
  # Needs to be able to read and watch for PVCs for auto-provisioning
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
      - update
  # Needs to be able to read StorageClasses, which contain some config options
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
  # Needs to be able to modify events, not sure why
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - update
      - patch
{{- end -}}

{{- define "nfs.Role" -}}
rules:
  # Gives the provisioner read/write access to endpoints within this namespace, this appears to be to do with Leader Election
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
{{- end -}}